- src/bring/2.Colors.md
- src/bring/_config/variables.css
- src/posten/2.Colors.md
- src/posten/_config/variables.css
The previous link blue `#4a90e2` has lower contrast than it should have. It will fail accessibility requirements when used on the default light gray background. This new hex value `#0066dd` has the same hue, but with increased saturation and decreased lightness. 
More details in issue: https://github.com/bring/hedwig/issues/100
> Make link blue pass WCAG 2.0 contrast requirements

- src/shared/components/hr/Hr.md
- src/shared/components/hr/hr.css
This adds a styles for a <hr> component with the lighter gray-color.
> Add HR with lighter gray color

- src/posten/2.Colors.md
- src/posten/_config/variables.css
According to Ingrid Arnesen, the primary dark color should be #CD291F.
> Update Posten primary dark

- src/shared/_config/variables.css
We have an issue in New Sende in the Native application where we don't want to use the Posten-font (Foundry Monoline), but we want to use a normal sans-serif font.
Without this added line, the font will fallback to a serif font which looks kinda terrible.
> Set sans-serif as default fallback font

- package.json
`npm run[-script]` exposes the version number from `package.json` as a environment variable called `$npm_package_version` (see `npm run env` for a full list). This pull requests simplifies the run targets by using this variable and removes the therefor obsolete script `getversion`.
> There's a build-in env-var for that.

- src/shared/components/autocomplete/autocomplete.css
- src/shared/components/list/List.md
- src/shared/components/list/list.css
- src/shared/layout/block/Block.md
- src/shared/layout/block/block.css
Added a new modifier to the block:
`.hw-block--px-fluid`
This behaves just like a container, so that it can be used to create the same side gutters, for example inside a gray box. Example:
> Block tweaks

- src/shared/components/dropdown/dropdown.js
It turns out that option.innerText has some extra whitespace while display = none.
This extra whitespace, somehow, gets converted into <br>s while assigning it to another element's innerText
Therefore .trim() is used to shave off the extra whitespace
> Fix display of placeholder for dropdown within a drawer

- src/shared/components/icon-link/Icon-link.md
- src/shared/components/icon-link/icon-link.css
- Background color 4% black on hover
- Remove white- and link-colored versions
> Cleanup and change hover for Icon link

- src/shared/components/icon-service/Icon-service.md
- src/shared/components/icon-service/icon-service.css
Remove icon specific coloring. This is provided through `hw-color-[color]`
> Add sizing modifier for hw-icon

- src/shared/components/figure/figure.css
enonic adds caption even if no captions are there
> Bug fix: Show figcaption only if content present

- src/shared/components/accordion/Accordion.md
- src/shared/components/accordion/accordion.js
Using index causes duplicate `id`s , which fails accessibility
> Replace index with random number to avoid duplicates

- src/shared/components/input/Input.md
- src/shared/guidelines/Layout.md
Fixed a small spelling mistake in layout.md and removed '' around
relative link in the input.md file as it caused the link to not work properly
> Fix link from layout to grid page and spelling

- src/shared/components/frame/frame.css
-ms-flex-preferred-size gets set to 0 by polyfill generator
which is incorrect
> IE flex basis issue fix

- src/shared/components/tab/tab.css
- Otherwise, non-selected tabs use to look the same as disabled. 
- Necessary for web accessibility ( WCAG )
> Update the color of the tabs to have better contrast

- src/shared/components/phone-input/Phone-input.md
- src/shared/components/phone-input/phone-input.css
Prefix for phone number must be long enough to support country codes that are five characters long (e.g "+1806")
> Prefix for phone number must be long enough

- src/bring/components/navbar/Navbar.md
- src/posten/components/navbar/Navbar.md
The code example for navbar without menu lacked a closing div
> Add closing div to navbar without menu example

- src/shared/components/link/Link.md
- src/shared/components/link/link.css
Request for a modifier that would hide the underline of links until
they are hovered. This modifier works together with other classes,
as all it does is affect the border-bottom-width attribute.
A demonstration was also added to the documentation.
> add a no-underline without hover modifier to hw-link

- src/shared/_config/variables.css
- src/shared/components/print/Print.md
- src/shared/components/print/print.css
- src/shared/guidelines/Utilities.md
- src/shared/utilities/css/print.css
- src/shared/utilities/css/responsive.css
A request came up in kp-suite about printed pages, which led to a
decision to start adapting Hedwig with some print functionality. These
is the initial features that will be included for print views:
- Automatically hide elements that are non-functional in print
(e.g. menu, footer links, buttons)
- Automatically expand accordions
- Hide mobile-only and desktop-only elements
- Screen-only class
- Print-only class
- Print view display modifiers
- Page breaks utilities
- Documentation
> start the print section of Hedwig

- src/shared/components/tab/tab.css
hide tab scrollbar in Edge/IE browsers
> hiding tab scrollbar in Edge/IE browsers

- src/bring/components/navbar/Navbar.md
- src/shared/components/navbar/navbar.css
Adding skip-to-main-content link in navbar after Logo
It gets the second Tab Order after Logo
> adding skip-to-main-content link in navbar

- server.js
This is hard to test locally, since the issue only appears on Heroku. Hopefully this will work.
> Allow loading assets on external sites from documentation

- src/shared/components/accordion/accordion.js
In react, sometimes the accordion content doesn't expand to content's height.
> On init, resize accordion if already initialised

- src/shared/components/navbar/navbar.js
This is required in the react applications to initialize the component as there is usually a delay or the component is loaded after the init in main.js is run.
> Expose init method for navbar

- src/shared/base/typography.css
Since font-family decides the weight of the font now, I removed some font-weight statements that are no longer necessary
> removed font weight where its obsolete

- src/shared/components/warning-banner/Warning-banner.md
- src/shared/components/warning-banner/warning-banner.css
- src/shared/components/warning-banner/warning-banner.js
Leave existing banner.css and banner.js, since there are many projects that still uses the Banner component.
hw-banner is used the following places:
- https://github.com/bring/tracking-frontend/blob/master/frontend/src/test/components/__snapshots__/ApplicationBanner.test.js.snap
- https://github.com/bring/e-porto/blob/master/frontend/digitalstamp/src/pages/dummy/Debug.js
- https://github.com/bring/norgespakke-liten/blob/master/frontend/src/components/Debug.tsx
- https://github.com/bring/kp-suite/blob/master/hedwig-commons/src/main/resources/site/parts/banner/banner.html
- https://github.com/bring/pmo-web-components/blob/master/library/src/components/pmo/ApplicationMessage/__snapshots__/ApplicationMessageBanner.test.tsx.snap
- https://github.com/bring/sende-express/blob/master/frontend/src/ …
> Rename Banner to Warning banner

- package-lock.json
- package.json
Still lots of vulnerabilities in this library, but they require major version bumps to be fixed.
> Bump core-js from vulnerable version and do npm audit fix
