src/bring/components/footer/footer.css

- Fill color for svgs in links
- Paddings
- Active background-color

Some adjustments for the mobile footer

---

src/shared/components/stickynav/stickynav.js
src/shared/components/tab/tab.js
src/shared/utilities/js/horizontalScroll/horizontalScroll.js
src/shared/utilities/js/horizontalScroll/index.js
src/shared/utilities/js/verticalScroll/index.js

Scroll the Tab horizontally to center the selected item when the screen is to narrow to show the whole Tab

Tab scroll

---

src/shared/components/drawer/drawer.css

The header was not showing.
Also there were some issues with weird scrollbars

Fix the header for drawer in IE

---

src/shared/_config/variables.css

Updated responsive ranges to avoid overlaps

updated responsive ranges

---

src/shared/components/list/List.md
src/shared/components/list/list.css

Added new modifier for list where we don't want bullets.
`hw-list hw-list--no-bullets`

New list modifier for no bullets

---

src/shared/base/colors.css
src/shared/base/typography.css
src/shared/components/list/List.md
src/shared/components/list/list.css
src/shared/guidelines/Typography.md

New modifier for text (`hw-text-primary`) as per request.

Typography tweaks

---

src/shared/_config/variables.css
src/shared/layout/block/Block.md
src/shared/layout/block/block.css
src/shared/layout/container/Container.md
src/shared/layout/container/container.css

- Implemented container and block changes.
- Updated docs

Finished container refactor

---

src/shared/components/autocomplete/autocomplete.css
src/shared/components/list/List.md
src/shared/components/list/list.css

- Added new `--light` modifier for list.
- Fixed bug where autosuggest suggestions would appear under a drop-down

List light

---

src/shared/components/banner/Banner.md
src/shared/components/banner/banner.css

Also added aria role and level for header as heading-2.

Banner header is now H2

---

src/shared/components/icon-functional/Icon-functional.md
src/shared/components/icon-functional/icon-functional.js

Added a new comments-alt icon for chatbot implementation

Adding new comments icon

---

src/shared/components/banner/banner.js

'contents' in line 123 was getting undefined if the expanded section was made optional. Added a condition check.

Banner expanded section made optional

---

src/shared/components/datepicker/Datepicker.md
src/shared/components/datepicker/datepicker.css
src/shared/components/icon-functional/Icon-functional.md
src/shared/components/icon-functional/icon-functional.js

- Better centering of the calendar icon in the input field
- Change calendar icon
- Bigger calendar icon

Adjustments on the calendar icon for datepicker

---

package-lock.json
src/shared/components/icon-functional/Icon-functional.md
src/shared/components/icon-functional/icon-functional.js

Add 'pause-circle' as a functional icon ( FontAwesome )

---

src/shared/utilities/js/findParent/findParent.js
src/shared/utilities/js/q/q.js
src/shared/utilities/js/qa/qa.js

This will make the following utilities available for use outside of Hedwig:
- hedwig.qa()
- hedwig.q()
- hedwig.findParent()

Export utilities qa, q and findParent from Hedwig

---

scripts/config/docs-html-bring.js
scripts/config/docs-html-posten.js
src/shared/components/datepicker/datepicker-example.js

Also update to the latest version of Pikaday

Make sure Pikaday elements are only initialized once

---

src/shared/components/figure/Figure.md
src/shared/components/figure/figure.css

Also some clean up:
- Width of image always 100%
- Remove full and large modifiers

Add a gradient overlay for hw-figure.

---

src/shared/components/trace/Trace.md
src/shared/components/trace/trace.css

added option to keep input field and button on the same line

Trace adjustments

---

src/shared/components/input/input.css

iPhone safari auto generates border-radius:5px

Fix iPhone round corner input issue

---

src/shared/components/drawer/Drawer.md
src/shared/components/drawer/drawer.css

Replaced animation with transition

Fix performance issue in IE

---

src/shared/components/button/button.css

Repositioning and increasing the size a bit

Restyle chaticon

---

package-lock.json
src/shared/components/icon-functional/Icon-functional.md
src/shared/components/icon-functional/icon-functional.js

This is to add an icon from Font awesome.

Add "shield-alt" as functional icon

---

src/bring/guidelines/Colors.md
src/posten/guidelines/Colors.md
src/shared/base/colors.css

adding new CSS classes for Responsive Background colours with opacity

adding Responsive Background colors with opacity

---

src/shared/components/tab/tab.css

Tab-color change and spacing between tabs decresed
removed span styling from css

Tab-color change and spacing between tabs decresed

---

src/shared/components/entrance-box/Entrance-box.md
src/shared/components/entrance-box/entrance-box.css

new entrance box component for frontpage.

new hw entrance-box component

---

src/shared/components/wysiwyg/wysiwyg.css

adding missing figcaption css under wysiwyg

adding figcaption css under wysiwyg

---

package-lock.json
scripts/concatcss.js
scripts/utilities/concat.js
scripts/watcher.js
src/shared/base/display.css
src/shared/layout/block/block.css

Display none bug

---

src/shared/components/icon-functional/Icon-functional.md
src/shared/components/icon-functional/icon-functional.js

Added three icons (archive, edit and exchange) from font awesome to hedwig

Added three new icons to hedwig

---

src/shared/components/modal/modal.css
src/shared/layout/grid/grid.css

This is needed after updating postcss-cssnext

Use calc for processing negative use of variables

---

src/hedwig-react.jsx
src/shared/react/Card-cta/Cta-Card-react.md
src/shared/react/Card-cta/CtaCard.jsx

Add react component for call to action cards,
it takes title and content as props

Create a react component for cta cards

---

src/bring/components/footer/Footer.md
src/posten/components/footer/Footer.md
src/shared/_config/sanitize-extra.css
src/shared/components/accordion/accordion.css
src/shared/components/curtain/curtain.css
src/shared/components/help-tip/help-tip.css
src/shared/components/navbar/navbar.css
src/shared/components/show-more/show-more.css
src/shared/components/some-buttons/some-buttons.css

Add `color: inherit` to buttons that need it.
Move `background-color: transparent` from sanitize-extra to the respective buttons

Button color

---

package-lock.json
package.json

Many packages now requires npm 6.8.0 and above

Update node to v10.16.0 and npm to 6.9.0

---

src/shared/components/banner/Banner.md
src/shared/components/banner/banner.css

Override browser default button background of white and use transparent instead for banner closing button.

Banner white lines

---

src/bring/components/table/table.css
src/shared/_config/variables.css
src/shared/base/typography.css
src/shared/components/table/Table.md
src/shared/components/table/table.css
src/shared/components/wysiwyg/wysiwyg.css

Tables
- new table `hw-table__column` (Vertical Table). 
- changing table-layout to fixed.
- adding hw-h6 style.
- link styling in the table cells.

New column table

---

src/shared/components/icon-functional/Icon-functional.md
src/shared/components/icon-functional/icon-functional.js

adding this icon https://fontawesome.com/icons/bullseye-arrow?style=solid - need it for the open tracking page (sporing.posten.no)
https://trello.com/c/RiI1dSJg/53-multiple-search-results

add icon fas fa-bullseye-arrow

---

src/shared/components/entrance-box/entrance-box.css

modified the color of the label

---

src/shared/components/icon-functional/Icon-functional.md
src/shared/components/icon-functional/icon-functional.js

This reverts commit c26d0565354093bf0f6df8d24f0101cdf0db43d5.

Revert "Add left arrow icon (#772)"

---

src/shared/components/table/table.css

Fix problems with words breaking in tables

Remove table-layout: fixed

---

src/shared/components/dropdown/dropdown.js

Enable bubbling of onChange to capture in react
Add null checks

Dropdown nullcheck

---

src/shared/_config/variables.css
src/shared/components/label/label.css

- Add one pixel to the font size
- Change color from dark gray to black

More visible labels for input fields

---

package.json

The resulting main.js remains unchanged after doing this update

Update @babel & plugins to 7.12.*

---

src/shared/components/accordion/accordion.js

Allows dirty initialize accordion when accordion items are lazy loaded

Allow dirty init in accordion

---

src/posten/_config/variables.css
src/shared/components/label/label.css

- Changed Posten input-accent / focus color to darker red
- If input had a validation arrorincluding the

Posten accent color change

---

src/shared/components/modal/modal.js

To manually init in react components

Export modal function

---

src/shared/components/icon-functional/icon-functional.js

Adding icons bell and wand-magic-sparkles for use in sende-frontend.

Add icons bell and wand-magic-sparkles

---

package-lock.json
package.json
src/shared/components/accordion/accordion.css
src/shared/components/navbar/navbar.js

- Revert "11.10.1"
- Revert "fix: Restyle the accordion arrow to the left (#1811)"
- Revert "Merge pull request #1810 from bring/search-focus"

reverting to 11.10.0 due to bug
